name: Unity

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Assets/UnityVoiceProcessor/**'
      - '!README.md'
      - '.github/workflows/unity.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'Assets/UnityVoiceProcessor/**'
      - '!README.md'
      - '.github/workflows/unity.yml'

jobs:
  playtest-linux:
    name: Run PlayTest unit tests on Linux
    runs-on: pv-android

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Run tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /home/picovoice/Unity/Hub/Editor/2019.4.34f1/Editor/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform StandaloneLinux64 -logFile -

    - name: Check Results
      run: sed -n 2p unityresults.xml | grep 'result="Passed"'

  playtest-mac:
    name: Run PlayTest unit tests on macOS
    runs-on: pv-ios

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Run tests
      run: /Applications/Unity/Hub/Editor/2019.4.34f1/Unity.app/Contents/MacOS/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform StandaloneOSX -logFile -

    - name: Check Results
      run: sed -n 2p unityresults.xml | grep 'result="Passed"'

  playtest-windows:
    name: Run PlayTest unit tests on Windows
    runs-on: pv-windows

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Run tests
      run: >
        & "C:\Program Files\Unity\Hub\Editor\2019.4.34f1\Editor\Unity.exe" -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform StandaloneWindows64 -logFile - | Out-Host

    - name: Check Results
      run: bash -c "sed -n 2p unityresults.xml | grep Passed"

  playtest-android:
    name: Run PlayTest unit tests on Android
    runs-on: pv-ios

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Start Emulator
      run: /Users/alirezakenarsari-anhari/Library/Android/sdk/emulator/emulator -avd Pixel_6_API_33 &

    - name: Run tests
      run: /Applications/Unity/Hub/Editor/2019.4.34f1/Unity.app/Contents/MacOS/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform Android -logFile -

    - name: Check Results
      run: sed -n 2p unityresults.xml | grep 'result="Passed"'