name: Unity Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.cs'
      - '**/*.cs'
      - '.github/workflows/unity-codestyle.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '**/*.cs'
      - '**/*.cs'
      - '.github/workflows/unity-codestyle.yml'

jobs:
  check-unity-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Codestyle
      run: dotnet format whitespace Assets/UnityVoiceProcessor --folder --verify-no-changes